// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonifiBackend.Infrastructure.Data;

#nullable disable

namespace PersonifiBackend.Infrastructure.Migrations
{
    [DbContext(typeof(PersonifiDbContext))]
    partial class PersonifiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PersonifiBackend.Core.Entities.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "CategoryId", "Period");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("PersonifiBackend.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#1a3a5f",
                            Icon = "🏠",
                            Name = "Housing",
                            Type = 1,
                            UserId = "google-oauth2|114831037037369295773"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#0f8a3c",
                            Icon = "🍔",
                            Name = "Food",
                            Type = 1,
                            UserId = "google-oauth2|114831037037369295773"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#c9a86e",
                            Icon = "🚗",
                            Name = "Transport",
                            Type = 1,
                            UserId = "google-oauth2|114831037037369295773"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#8b5cf6",
                            Icon = "🎮",
                            Name = "Entertainment",
                            Type = 1,
                            UserId = "google-oauth2|114831037037369295773"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#b54248",
                            Icon = "🛍️",
                            Name = "Shopping",
                            Type = 1,
                            UserId = "google-oauth2|114831037037369295773"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#14b8a6",
                            Icon = "💡",
                            Name = "Utilities",
                            Type = 1,
                            UserId = "google-oauth2|114831037037369295773"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#0f8a3c",
                            Icon = "💰",
                            Name = "Salary",
                            Type = 0,
                            UserId = "google-oauth2|114831037037369295773"
                        },
                        new
                        {
                            Id = 8,
                            Color = "#c9a86e",
                            Icon = "💼",
                            Name = "Freelance",
                            Type = 0,
                            UserId = "google-oauth2|114831037037369295773"
                        });
                });

            modelBuilder.Entity("PersonifiBackend.Core.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "TransactionDate");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("PersonifiBackend.Core.Entities.Budget", b =>
                {
                    b.HasOne("PersonifiBackend.Core.Entities.Category", "Category")
                        .WithMany("Budgets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PersonifiBackend.Core.Entities.Transaction", b =>
                {
                    b.HasOne("PersonifiBackend.Core.Entities.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PersonifiBackend.Core.Entities.Category", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
